version: "3"
services:
  dashboard:
    build: ./dashboard
    command: npm start
    ports: 
      - "5000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis  
  redis:
    image: redis
    container_name: redis_cache
    expose:
      - 6379
      